### ISSUE TITLE
Restrict to a subset of object classes

### ISSUE THREAD

**Issue by paviddavid** [meyerjo/deepdrive_dataset_tfrecord#1]
Hello @meyerjo. Thanks for this repo. 
Is it possible to also extract just a subset of object classes in scope of a further condition to use? I want only to create a tfrecord file for the object classes pedestrian, car and traffic sign in order to use the data to compare it to other models that are only trained on the aforementioned classes. 

Thanks a lot in advance
Best Regards

**Comment by meyerjo** [comment]
Should be fixed with the latest commit you can now append --classes=bus,car
